name: hierarchical-rl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.8.0
  - cudatoolkit=11.1
  - numpy>=1.19.0
  - matplotlib>=3.3.0
  - pyyaml>=5.4.1
  - tqdm>=4.60.0
  - pip
  - pip:
    - sumolib>=1.8.0
    - traci>=1.8.0

